import React, { useState, useEffect, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
  PhoneCall,
  PhoneIncoming,
  PhoneOff,
  MessageSquare,
  Mic,
  Volume2,
  RefreshCw,
  Clock,
  Send,
  ThumbsUp,
  Activity,
  Smile,
  AlertCircle,
  Play,
  Pause,
  Plus,
  Trash2,
  Eye,
  CheckCircle2,
  XCircle,
  HelpCircle,
  FileSpreadsheet,
  Check,
  ChevronRight,
  ChevronDown,
  ArrowLeft,
  ChevronLeft,
  Inbox,
  History,
  PhoneForwarded,
  MessageCircleQuestion,
  GitBranch,
}